{
  pkgs,
  inputs,
  lib,
  ...
}: {
  imports = [
    ./binds.nix
    ./look-and-feel.nix
    ./hyprpanel.nix
  ];

  services.hyprpaper.enable = true;
  programs.hyprlock.enable = true;

  programs.fuzzel.enable = true;
  services.cliphist.enable = true;

  programs.keepassxc.enable = true;

  home.packages = with pkgs; [
    inputs.rcheck.outputs.packages.${pkgs.system}.default

    kdePackages.dolphin
    bemoji
    wl-clipboard
    tor-browser
    protonvpn-gui
    fluffychat
    obsidian
    qbittorrent
    mullvad-browser
    yubioath-flutter
    yubikey-manager
  ];

  wayland.windowManager.hyprland = {
    enable = true;
    systemd = {
      enable = true;
      variables = ["--all"];
    };

    settings = {
      autogenerated = 0;

      monitor = lib.mkDefault ",preferred,auto,1";

      "$terminal" = "wezterm";
      "$fileManager" = "dolphin";

      env = [
        "XDG_SESSION_TYPE,wayland"
        "QT_QPA_PLATFORM,wayland"
        "HYPRCURSOR_THEME,rose-pine-hyprcursor"
        "XCURSOR_SIZE,24"
        "HYPRCURSOR_SIZE,24"
        "GTK_CSD,0"
      ];

      input = {
        kb_layout = "gb";
        follow_mouse = 1;

        sensitivity = 0;

        touchpad = {
          natural_scroll = true;
        };
      };

      windowrule = [
        "suppressevent maximize, class:.*"
        "nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0"
      ];
    };
  };
}
