{pkgs, ...}: {
  imports = [
    ./binds.nix
    ./look-and-feel.nix
    ./hyprpanel.nix
    ./hyprpaper.nix
  ];

  programs.wofi.enable = true;
  services.cliphist.enable = true;

  home.packages = with pkgs; [
    kdePackages.dolphin
    bemoji
    wl-clipboard
  ];

  wayland.windowManager.hyprland = {
    enable = true;
    systemd = {
      enable = true;
      variables = ["--all"];
    };

    settings = {
      autogenerated = 0;

      monitor = ",preferred,auto,1";

      "$terminal" = "kitty";
      "$fileManager" = "dolphin";

      env = [
        "XDG_SESSION_TYPE,wayland"
        "QT_QPA_PLATFORM,wayland"
        "HYPRCURSOR_THEME,rose-pine-hyprcursor"
        "XCURSOR_SIZE,24"
        "HYPRCURSOR_SIZE,24"
      ];

      input = {
        kb_layout = "gb";
        follow_mouse = 1;

        sensitivity = 0;

        touchpad = {
          natural_scroll = true;
        };
      };

      windowrule = [
        "suppressevent maximize, class:.*"
        "nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0"
      ];
    };
  };
}
